### PR TITLE
Added chain matrix in c and java

### PR DESCRIPTION
**Pull request by NavyaIyanampudi**

### CODE REVIEW

**Comment by YashJain2** [comment]
Please provide output and discription

**Comment by YashJain2** [comment]
Happy more PRs awaiting ahead

**Comment by NavyaIyanampudi** [comment]
Yeah sure

**Review by YashJain2 — COMMENTED** [review]
Please just put comments for better code accessibility

**Comment by NavyaIyanampudi** [comment]
Sure,Sorry for inconvinience

**Pull request merged**
